### ISSUE TITLE
info(dep): Application-utility & Gnome-layout-switcher not installed

### ISSUE THREAD

**Issue by Bad3r** [KoraggKnightWolf/archlinux-hello#1]
```sh
❯ archlinux-hello
Info: Application-utility not installed
Info: Gnome-layout-switcher not installed
```

What exactly is `Application-utility`? And to confirm these are optional deps?

**Comment by KoraggKnightWolf** [comment]
This project is a fork of manjaro-hello from https://gitlab.manjaro.org/applications/manjaro-hello and a lot of things were just taken over, including it searching for the programs you see in that output. 
It is searching for Gnome-layout-switcher in: https://github.com/KoraggKnightWolf/archlinux-hello/blob/main/src/archlinux_hello.py#L67-L90
as well as for Application-utility in: https://github.com/KoraggKnightWolf/archlinux-hello/blob/main/src/archlinux_hello.py#L91-L120

Unfortunately my coding skills are very low, but it should be safe if I just remove those respective sections? I have not so far as to avoid possible breakage caused by myself.

They are however completely optional deps, archlinux-hello will run even without those installed.

I hope this could clear some things up at least, apologies for the confusion, and thanks a lot for taking interest in this project. It is my first one in the AUR.

Regards,

Koragg

**Comment by Bad3r** [comment]
> ..it should be safe if I just remove those respective sections? I have not so far as to avoid possible breakage caused by myself.

I am not sure, but removing it and testing will give a clear answer.   
 

> It is my first one in the AUR.

That's awesome congrats! I randomly came across your project and I wanted to check it out. Great progress so far!

**Comment by KoraggKnightWolf** [comment]
I have now removed the parts of the code that reference and make use of gnome-layout-switcher and Application-utility which do not exist on Arch Linux (not even in the AUR it seems). Thanks a lot for bringing up the issue, as I was wondering if others might be bothered by it (fixing code is for me really just trial and error at this point in time unfortunately). 
The package has been updated in the AUR and the PKGBUILD in my dedicated github repo for it has also been updated. The project is now at version 0.8.2 to reflect the changes made.

Regards,

Koragg

**Comment by Bad3r** [comment]
Great! 

> ..as I was wondering if others might be bothered by it

It's not an issue of that it bothered me I just was wondering if I needed to install extra packages to get the full experience. Since the readme didn't mention ignoring these warning I thought I should bring it up in case it was a packaging issue. 

> (fixing code is for me really just trial and error at this point in time unfortunately).

Don't be so hard on yourself. Fixing code is a trial and error for everyone. There is a popular development concept called Test Driven Development (TDD).

> Test-driven development (TDD) is a software development process relying on software requirements being converted to test cases before software is fully developed, and tracking all software development by repeatedly testing the software against all test cases. This is as opposed to software being developed first and test cases created later.

Many large projects and companies use this method of development. Which is a trial and error based concept.
You write the test. Then write the code. Run the test. If it fails fix the code and so on.
